spring:
  application:
    name: flightapp-search-service
  datasource:
    url: jdbc:mysql://localhost:3306/flightapp?useSSL=false
    username: root
    password: root
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: update
server:
  port: 8085
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8081/eureka
            
# App Properties
com:
  flightapp:
    jwtSecret: flightappSecretKey
    jwtExpirationMs: 60000

